### ISSUE TITLE
github上传图片失败

### ISSUE THREAD

**Issue by minglinpop** [hibikilogy/spiders#1]
你好,关于github上传图片报错
使用 GitHub 作为图床失败（[Errno 2] No such file or directory: 'minglinpop.github.io/xy-search/images/2card5130940_web.png'），已使用原链接。
关于github上传图片，需要额外的做哪些步骤呢？

**Comment by inchei** [comment]
```
.
├─hibikilogy.github.io
│  └─images
└─spiders（当前目录）
```
目前的设计是要满足这样的目录，因为一般用这个工具都需要也把网站的仓库 clone 下来。我忘记说明了，谢谢提醒。
